language: cpp
compiler:
  - gcc
install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install python3
before_script:
  - sudo add-apt-repository ppa:nginx/stable -y
  - sudo apt-get update -q
  - sudo apt-get install nginx netcat
script:
  - ./runtests
branches:
  only:
    - master
notifications:
  #irc:
    #channels:
      #- "chat.freenode.net#mwa"
    #template:
      #- "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
  email:
    recipients:
      - jkaluza@redhat.com
    on_success: always
    on_failure: always
